DataVisualizer/urls.py
from django.contrib import admin
from django.urls import path
from home import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homePage, name='home_page'),
    path('add/', views.addData, name='add_data'),
    path('update/<int:pk>/', views.updateData, name='add_data'),
    path('delete/<int:pk>/', views.deleteData, name='delete_data'),
]

home/models.py
from django.db import models

class StockMarket(models.Model):

    date = models.DateField(auto_now_add=False, auto_now=False, null=True)
    trade_code = models.CharField(max_length=20)
    high = models.FloatField(null=True)
    low = models.FloatField(null=True)
    open = models.FloatField(null=True)
    close = models.FloatField(null=True)
    volume = models.IntegerField(null=True)

    def __str__(self):
        return f'Date : {self.date} - Code: {self.trade_code}'

home/forms.py
from django import forms
from .models import StockMarket


class DataForm(forms.ModelForm):
    class Meta:
        model = StockMarket
        fields = ['date','trade_code','high','low','open','close','volume']

home/views.py
from django.shortcuts import render, redirect
from .models import StockMarket
from .forms import DataForm
from django.core.paginator import Paginator, EmptyPage
from .filters import DataFilter

# Function to load data from model StockMarket
def homePage(request):
    data = StockMarket.objects.all()

    myFilter = DataFilter(request.GET,queryset=data)
    data = myFilter.qs

    context = {
        'data': data,
        'filter': myFilter,
        'dropdown': StockMarket.objects.values('trade_code').distinct(),
    }
    return render(request, 'home/home_page.html', context)

# Adds new data to the database.
def addData(request):
    if request.method == 'POST':
        form = DataForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = DataForm()
    return render(request, 'home/add_data.html', {'form':form})


#Updates the data of the database
def updateData(request, pk):
    data = StockMarket.objects.get(id=pk)
    form = DataForm(instance=data)

    if request.method == 'POST':
        form = DataForm(request.POST, instance=data)
        if form.is_valid():
            form.save()
            return redirect('/')

    value = {'form':form}
    return render(request, 'home/add_data.html', value)


#Deletes a particular data
def deleteData(request, pk):
    data = StockMarket.objects.get(id=pk)

    if request.method == 'POST':
        data.delete()
        return redirect('/')

    value = {'item':data}
    return render(request, 'home/delete_data.html', value)

templates/home/add_data.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Add Data
{% endblock %}

{% block content %}
    <div class="container mb-3 mt-5">
    <div class="card text-black border-primary">
    <div class="card-header">
        <strong>
            Insert Data
        </strong>
    </div>

            <div class="card-body">
                <form method="POST">
                    <fieldset class="form-group">
                        {% csrf_token %}
                        {{ form|crispy }}
                    </fieldset>
                    <br>
                    <input class="btn btn-success" type="submit" value="Add Data">
                </form>
            </div>
</div>
</div>


{% endblock %}

templates/home/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- Chart.js CDN -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
    <title>
        {% block title %}

        {% endblock %}
    </title>

  </head>
  <body>

    <div>
        {% block content %}

        {% endblock %}
    </div>
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </body>
</html>

templates/home/delete_data.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
    Add Data
{% endblock %}

{% block content %}

    <div class="container mb-3 mt-5">
        <div class="card text-black border-primary">
            <div class="card-header">
                <strong>
                    Delete Data
                </strong>
            </div>

            <div class="card-body">
                <h5>Are you sure you want to delete "{{ item }}?"</h5>

                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <a class="btn btn-success" href="{% url 'home_page' %}">Cancel</a>
                        <input class="btn btn-danger" type="submit" value = "Confirm">
                    </form>
            </div>
</div>
</div>

{% endblock %}

templates/home/home_page.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Visual Data
{% endblock %}

{% block content %}

        <h1 style="text-align:center">
            Data Visualization app with Django
        </h1>

        <div class="card text-center" style="margin-left: 20%;margin-right: 20%;">
          <div class="card-header">
            Data Insertion Page
          </div>
          <div class="card-body">
            <h5 class="card-title">Insert Data</h5>
            <p class="card-text">Insert data here using all the fields. This link will take you to another page.</p>
            <a href="{% url 'add_data' %}" class="btn btn-primary">Insert Data</a>
          </div>
        </div>

        <div class="mt-5 ml-5 mr-5 mb-5" style="text-align:center">
            <form method="get">
                {% comment %} {{filter.form|crispy}} {% endcomment %}
                <select class="form-select" name="trade_code" id="id_trade_code">
                    <option selected>Select a trade code</option>
                    {% for i in dropdown %}<option value="{{i.trade_code}}">{{i.trade_code}}</option>{% endfor %}
                </select>
                <button class="btn btn-primary" type="submit">Search</button>
            </form>
        </div>

        <div class="mt-5 ml-5 mr-5 mb-5">
            <h4 style="text-align:center"> Mixed Chart </h4>
        {% include 'home/includes/mixed_chart.html' %}
        </div>

        <div class="mt-5 ml-5 mr-5 mb-5">
            <h4 style="text-align:center"> Bar Chart </h4>
        {% include 'home/includes/bar_chart.html' %}
        </div>

    <div class="container mt-5">
        <table id="table_id" class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Trade Code</th>
                    <th>High</th>
                    <th>Low</th>
                    <th>Open</th>
                    <th>Close</th>
                    <th>Volume</th>
                    <th>Actions</th>
                </tr>
            </thead>
            {% for d in data %}
            <tbody>
            <tr>
                <td>{{d.date}}</td>
                <td>{{ d.trade_code }}</td>
                <td>{{ d.high }}</td>
                <td>{{ d.low }}</td>
                <td>{{ d.open }}</td>
                <td>{{ d.close }}</td>
                <td>{{ d.volume }}</td>
                <td>
                    <a class="btn btn-success btn-sm" href="{% url 'add_data' d.id %}">Edit</a>
                    <a class="btn btn-danger btn-sm" href="{% url 'delete_data' d.id %}">Delete</a>
                </td>
            </tr>
            </tbody>
            {% endfor %}
        </table>

<!--        <div>-->
<!--            {% if data.has_previous %}-->
<!--                <a class="btn btn-primary btn-sm" href="{% url 'home_page' %}?page={{data.previous_page_number}}">Previous Page</a>-->
<!--            {% endif %}-->
<!--            {% if data.has_next %}-->
<!--                <a class="btn btn-primary btn-sm" href="{% url 'home_page' %}?page={{data.next_page_number}}">Next Page</a>-->
<!--            {% endif %}-->
<!--        </div>-->

    </div>
{% endblock %}

templates/home/includes/bar_chart.html
<canvas id="barChart" width="200" height="100"></canvas>
    <script>
                        var ctx = document.getElementById('barChart').getContext('2d');
                        var barChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: [{% for d in data %} '{{ d.trade_code }}', {% endfor %}],

                                datasets: [{
                                type: 'bar',
                                    label: 'Amount of Volumes / 1000',
                                    data: [{% for d in data %} {{ d.volume }}/1000, {% endfor %} ],
                                    backgroundColor: [
                                    <!-- red -->
                                        'rgba(255, 99, 132)',
                                    <!-- green -->
                                        'rgba(75, 192, 192)',
                                    ],
                                },
                                ]
                            },
                            options: {
                                scales: {
                                    y: {
                                        beginAtZero: true
                                    }
                                }
                            }
                        });
                    </script>

templates/home/includes/mixed_chart.html
<canvas id="mixedChart" width="200" height="100"></canvas>
    <script>
                        var ctx = document.getElementById('mixedChart').getContext('2d');
                        var mixedChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: [{% for d in data %} '{{ d.date }}', {% endfor %}],

                                datasets: [{
                                type: 'bar',
                                    label: 'Amount of Volumes / 10k',
                                    data: [{% for d in data %} {{ d.volume }}/100000, {% endfor %} ],
                                    backgroundColor: [
                                    <!-- red -->
                                        'rgba(255, 99, 132)',
                                    <!-- green -->
                                        'rgba(75, 192, 192)',
                                    ],
                                },
                                {
                                type: 'line',
                                    label: 'high',
                                    data: [{% for d in data %} {{ d.high }}, {% endfor %} ],
                                    backgroundColor: [
                                    <!-- blue -->
                                        'rgba(54, 162, 235)',
                                    ],
                                },
                                {
                                type: 'line',
                                    label: 'low',
                                    data: [{% for d in data %} {{ d.low }}, {% endfor %} ],
                                    backgroundColor: [
                                    <!-- blue -->
                                        'rgb(255, 159, 64)',
                                    ],
                                },
                                {
                                type: 'line',
                                    label: 'open',
                                    data: [{% for d in data %} {{ d.open }}, {% endfor %} ],
                                    backgroundColor: [
                                    <!-- blue -->
                                        'rgb(255, 205, 86)',
                                    ],
                                },
                                {
                                type: 'line',
                                    label: 'close',
                                    data: [{% for d in data %} {{ d.close }}, {% endfor %} ],
                                    backgroundColor: [
                                        'rgb(153, 102, 255)',
                                    ],
                                },
                                ]
                            },
                            options: {
                                scales: {
                                    y: {
                                        beginAtZero: true
                                    }
                                }
                            }
                        });
                    </script>